<a href="https://colab.research.google.com/github/Gabriel07G/Gabriel07G/blob/main/Starbucks__LTV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Predicting Customer Lifetime Value***

In [13]:
#CARRREGANDO E VISUALIZANDO OS DADOS.

from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import os
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn.metrics

raw_data = pd.read_csv("_starbucks.csv")
raw_data.dtypes

USER_ID    object
Mes_1       int64
Mes_2       int64
Mes_3       int64
Mes_4       int64
Mes_5       int64
Mes_6       int64
LTV         int64
dtype: object

In [5]:
raw_data.head()

  USER_ID  Mes_1  Mes_2  Mes_3  Mes_4  Mes_5  Mes_6    LTV
0  SB1001    143     68    193     93    168     68  13118
1  SB1002     18     43    143    193    168    193   9368
2  SB1003     68    143      0     18     68     18   5149
3  SB1004    193    184     18     93     68    143  11749
4  SB1005    210    187    118     68    168    193  15518

In [14]:
# FAZENDO UMA ANÁLISE CORRELACIONAL( CORRELATION ANALYSIS )

cleaned_data = raw_data.drop("USER_ID",axis=1)
cleaned_data .corr()['LTV']

Mes_1    0.747470
Mes_2    0.315811
Mes_3    0.393450
Mes_4    0.280002
Mes_5    0.368906
Mes_6    0.370982
LTV      1.000000
Name: LTV, dtype: float64

In [15]:
# FAZER A DIVISÃO DOS DADOS EM TREINAMENTO E TESTE!

predictors = cleaned_data.drop('LTV', axis=1)
target = cleaned_data.LTV

pred_train, pred_test, tar_train, tar_test = train_test_split(predictors, target, test_size=.1)
print("Predictor - Training : ", pred_train.shape, "Predictor - Testing : ", pred_test.shape)

Predictor - Training :  (77, 6) Predictor - Testing :  (9, 6)

In [17]:
# CONSTRUIR E TESTAR O MODELO.

model = LinearRegression()
model.fit(pred_train, tar_train)
print("Coeficients: \n", model.coef_)
print("Intercept: ", model.intercept_)

#TESTAR NOS DADOS DE TESTE.

predictions = model.predict(pred_test)
predictions

sklearn.metrics.r2_score(tar_test, predictions)

Coeficients:
 [35.29099612 10.52679087 15.73540076 12.8957201   7.21555741  6.95921006]
Intercept:  317.83089862084125

0.9036062133567915

In [21]:
# PREVENDO PARA UMA NOVO CLIENTE

new_data = np.array([120,80,90,200,0,0]).reshape(1, -1)
new_pred = model.predict(new_data)
print(" O LTV desse consumidor é : $", new_pred[0])

 O LTV desse consumidor é : $ 9390.223791702543

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(